Remove depreciated list() function.
terraform-google-modules/terraform-google-log-export pull request #92
Opened 2021-05-07 00:43 UTC by grugnog

This should address the Terraform 1.15 compatibility issue described in #89

2021-05-07 06:09 UTC, morgante requested changes

2021-05-07 06:09 UTC, morgante commented on main.tf
> +  log_sink_writer_identity = local.is_project_level ? element(concat(google_logging_project_sink.sink.*.writer_identity, []), 0) : local.is_folder_level ? element(concat(google_logging_folder_sink.si
The intention is to have a list of one empty string, so this is better:
```suggestion
  log_sink_writer_identity = local.is_project_level ? element(concat(google_logging_project_sink.sink.*.writer_identity, []), 0) : local.is_folder_level ? element(concat(google_logging_folder_sink.sink.*.writer_identity, []), 0) : local.is_org_level ? element(concat(google_logging_organization_sink.sink.*.writer_identity, []), 0) : local.is_billing_level ? element(concat(google_logging_billing_account_sink.sink.*.writer_identity, [""]), 0) : ""
```

2021-05-07 20:35 UTC, grugnog commented
@morgante updated, thanks!

2021-05-10 17:56 UTC, morgante approved these changes
Thanks!

2021-05-10 17:57 UTC, merged